{
 "title": "Nvidia / Node / GPU / Type / Slot",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(DCGM_FI_DEV_GPU_TEMP, instance)"
    }
   },
   {
    "name": "gpu",
    "query": {
     "query": "query_result(DCGM_FI_DEV_GPU_TEMP{instance=\"$node\"})"
    }
   },
   {
    "name": "slot",
    "query": {
     "query": "query_result(DCGM_FI_DEV_GPU_TEMP{instance=\"$node\", modelName=\"$gpu\"})"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "GPU temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{instance=~\"$node\", modelName=~\"$gpu\", gpu=\"$slot\"}",
     "legendFormat": "Slot {{gpu}} | {{pod}}"
    }
   ]
  },
  {
   "title": "GPU power usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE{instance=~\"$node\", modelName=~\"$gpu\", gpu=\"$slot\"}",
     "legendFormat": "Slot {{gpu}} | {{pod}}"
    }
   ]
  },
  {
   "title": "GPU SM clocks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_SM_CLOCK{instance=~\"$node\", modelName=~\"$gpu\", gpu=\"$slot\"} * 1000000",
     "legendFormat": "Slot {{gpu}} | {{pod }}"
    }
   ]
  },
  {
   "title": "GPU framebuffer mem used",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_FB_USED{instance=~\"$node\", modelName=~\"${gpu}\", gpu=\"$slot\"}",
     "legendFormat": "Slot {{gpu}} | {{pod}}"
    }
   ]
  }
 ]
}