{
 "title": "Nvidia / Node / GPU / All",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(DCGM_FI_DEV_GPU_TEMP, instance)"
    }
   },
   { "name": "gpu", "query": { "query": "label_values(gpu)" } }
  ]
 },
 "panels": [
  {
   "title": "GPU temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{instance=~\"$node\", gpu=~\"$gpu\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU avg. temp",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_TEMP{instance=~\"$node\", gpu=~\"$gpu\"})"
    }
   ]
  },
  {
   "title": "GPU power usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE{instance=~\"$node\", gpu=~\"$gpu\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU power total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_POWER_USAGE{instance=~\"$node\", gpu=~\"$gpu\"})"
    }
   ]
  },
  {
   "title": "GPU SM clocks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_SM_CLOCK{instance=~\"$node\", gpu=~\"$gpu\"} * 1000000",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU framebuffer mem used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_FB_USED{instance=~\"$node\", gpu=~\"$gpu\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  }
 ]
}