{
 "title": "Jenkins / Node / Resources",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "jenkins_cluster",
    "query": {
     "query": "query_result(default_jenkins_up)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vm_uptime_milliseconds{instance=\"$jenkins_cluster\", job=\"jenkins\"}"
    }
   ]
  },
  {
   "title": "Health",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jenkins_health_check_score{instance=\"$jenkins_cluster\"}"
    }
   ]
  },
  {
   "title": "Running jenkins builds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "jenkins_node_count_value{instance=\"$jenkins_cluster\"}",
     "legendFormat": "Nodes"
    }
   ]
  },
  {
   "title": "Nodes offline",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "jenkins_node_offline_value{instance=\"$jenkins_cluster\"}",
     "legendFormat": "Nodes"
    }
   ]
  },
  {
   "title": "JNLP availability in kubernetes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "targets": [
    { "expr": "jenkins_jnlp_status", "legendFormat": "jnlp availability" }
   ]
  },
  {
   "title": "Jenkins health check score",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "jenkins_health_check_score{instance=\"$jenkins_cluster\"}",
     "legendFormat": "health check score"
    }
   ]
  },
  {
   "title": "Delta queue size [3m]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "delta(jenkins_queue_size_value{instance=\"$jenkins_cluster\"}[3m])",
     "legendFormat": "Delta queue size"
    }
   ]
  },
  {
   "title": "VM CPU load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "vm_cpu_load{instance=\"$jenkins_cluster\"}",
     "legendFormat": "vm cpu load"
    }
   ]
  },
  {
   "title": "System CPU load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_cpu_load{instance=\"$jenkins_cluster\"}",
     "legendFormat": "system cpu load"
    }
   ]
  },
  {
   "title": "VM memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "vm_memory_total_used{instance=\"$jenkins_cluster\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Queue size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "jenkins_queue_size_value{instance=\"$jenkins_cluster\"}",
     "legendFormat": "Queue size"
    }
   ]
  },
  {
   "title": "JVM memory bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{instance=\"$jenkins_cluster\"}",
     "legendFormat": "{{area}}"
    }
   ]
  },
  {
   "title": "Jenkins disk usage in Kubernetes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "default_jenkins_disk_usage_bytes{directory=\"JENKINS_HOME\"}",
     "legendFormat": "{{directory}}"
    }
   ]
  },
  {
   "title": "Durations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processing speed [1m]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(jenkins_job_building_duration_count{instance=\"$jenkins_cluster\"}[1m])",
       "legendFormat": "Speed"
      }
     ]
    },
    {
     "title": "Job queue duration",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 6, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jenkins_job_queuing_duration{instance=\"$jenkins_cluster\"}"
      }
     ]
    },
    {
     "title": "Queued rate [1m]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(jenkins_job_queuing_duration_count{instance=\"$jenkins_cluster\"}[1m])",
       "legendFormat": "Rate"
      }
     ]
    },
    {
     "title": "Job total duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(jenkins_job_total_duration_count{instance=\"$jenkins_cluster\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Job building duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(jenkins_job_building_duration_count{instance=\"$jenkins_cluster\"}[$__rate_interval])"
      }
     ]
    },
    {
     "title": "Blocked duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(jenkins_job_blocked_duration_count{instance=\"$jenkins_cluster\"}[$__rate_interval])"
      }
     ]
    }
   ]
  },
  {
   "title": "Executors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "jenkins_executor_count_value{instance=\"$jenkins_cluster\"}"
      }
     ]
    },
    {
     "title": "Free",
     "type": "stat",
     "gridPos": { "h": 7, "w": 8, "x": 4, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "jenkins_executor_free_value{instance=\"$jenkins_cluster\"}"
      }
     ]
    },
    {
     "title": "In-use",
     "type": "stat",
     "gridPos": { "h": 7, "w": 8, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "jenkins_executor_in_use_value{instance=\"$jenkins_cluster\"}"
      }
     ]
    },
    {
     "title": "Queue size",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "jenkins_queue_size_value{instance=\"$jenkins_cluster\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Total jobs in cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total jobs",
     "type": "stat",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 27 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "jenkins_runs_total_total{instance=\"$jenkins_cluster\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Sucessful jobs",
     "type": "stat",
     "gridPos": { "h": 7, "w": 5, "x": 5, "y": 27 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "jenkins_runs_success_total{instance=\"$jenkins_cluster\"}"
      }
     ]
    },
    {
     "title": "Aborted jobs",
     "type": "stat",
     "gridPos": { "h": 7, "w": 5, "x": 10, "y": 27 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "jenkins_runs_aborted_total{instance=\"$jenkins_cluster\"}"
      }
     ]
    },
    {
     "title": "Unstable jobs",
     "type": "stat",
     "gridPos": { "h": 7, "w": 5, "x": 15, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "jenkins_runs_unstable_total{instance=\"$jenkins_cluster\"}"
      }
     ]
    },
    {
     "title": "Unstable jobs",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "jenkins_runs_unstable_total{instance=\"$jenkins_cluster\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Plugins",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 155 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "jenkins_plugins_active{instance=\"$jenkins_cluster\"}"
      }
     ]
    },
    {
     "title": "Inactive",
     "type": "stat",
     "gridPos": { "h": 7, "w": 8, "x": 4, "y": 155 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "jenkins_plugins_inactive{instance=\"$jenkins_cluster\"}"
      }
     ]
    },
    {
     "title": "Update",
     "type": "stat",
     "gridPos": { "h": 7, "w": 8, "x": 12, "y": 155 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "jenkins_plugins_withUpdate{instance=\"$jenkins_cluster\"}"
      }
     ]
    },
    {
     "title": "Failed",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 155 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "jenkins_plugins_failed{instance=\"$jenkins_cluster\"}"
      }
     ]
    }
   ]
  }
 ]
}