---
- name: Setting DNS
  hosts: all
  gather_facts: true
  become: true
  vars:
    dns_servers: "10.1.50.10 10.1.50.11 10.1.50.12"
  handlers:
    - name: Restart systemd resolved
      ansible.builtin.systemd:
        name: systemd-resolved
        state: restarted
  tasks:
    - name: Modify systemd resolved config
      ansible.builtin.lineinfile:
        path: /etc/systemd/resolved.conf
        regexp: '^DNS='
        line: "DNS={{ dns_servers }}"
      register: resolved_config_changed

    - name: Remove /etc/resolv.conf
      ansible.builtin.file:
        path: /etc/resolv.conf
        state: absent
      when: resolved_config_changed.changed

    - name: Create a symlink
      ansible.builtin.file:
        src: /run/systemd/resolve/resolv.conf
        dest: /etc/resolv.conf
        state: link
        force: yes
      notify: Restart systemd resolved
      when: resolved_config_changed.changed
