{
 "title": "Gerrit / Overview",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Gerrit Instance",
    "query": {
     "query": "label_values(git_upload_pack_phase_writing_total, instance)"
    }
   },
   {
    "name": "replica",
    "label": "Replica",
    "query": {
     "query": "label_values(git_upload_pack_phase_writing_total{instance=\"$instance\"}, replica)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "instance",
   "collapsed": true,
   "panels": [
    {
     "title": "Gerrit Version",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "max(gerrit_build_info{instance=\"$instance\",replica=\"$replica\"}) by (instance, version, revision, javaversion)"
      }
     ]
    },
    {
     "title": "Gerrit availability history",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 21, "x": 3, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "up{instance=\"$instance\",replica=\"$replica\"}*100",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Java Version",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "max(gerrit_build_info{instance=\"$instance\",replica=\"$replica\"}) by (instance, version, revision, javaversion)"
      }
     ]
    },
    {
     "title": "Gerrit Availability",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg_over_time(up{instance=\"$instance\",replica=\"$replica\"}[$__range])*100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Gerrit Events",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(events_change_merged_total{instance=\"$instance\", replica=\"$replica\"}[$__range])",
       "legendFormat": "change merged"
      },
      {
       "expr": "increase(events_comment_added_total{instance=\"$instance\", replica=\"$replica\"}[$__range])",
       "legendFormat": "comment added"
      },
      {
       "expr": "increase(events_patchset_created_total{instance=\"$instance\",replica=\"$replica\"}[$__range])",
       "legendFormat": "patchset created"
      },
      {
       "expr": "increase(events_change_abandoned_total{instance=\"$instance\",replica=\"$replica\"}[$__range])",
       "legendFormat": "change abandoned"
      },
      {
       "expr": "increase(events_ref_replicated_total{instance=\"$instance\",replica=\"$replica\"}[$__range])",
       "legendFormat": "ref replicated"
      },
      {
       "expr": "increase(events_ref_updated_total{instance=\"$instance\",replica=\"$replica\"}[$__range])",
       "legendFormat": "ref updated"
      },
      {
       "expr": "increase(events_reviewer_added_total{instance=\"$instance\",replica=\"$replica\"}[$__range])",
       "legendFormat": "reviewer added"
      },
      {
       "expr": "increase(events_reviewer_deleted_total{instance=\"$instance\",replica=\"$replica\"}[$__range])",
       "legendFormat": "reviewer deleted"
      },
      {
       "expr": "increase(events_topic_changed_total{instance=\"$instance\",replica=\"$replica\"}[$__range])",
       "legendFormat": "topic changed"
      },
      {
       "expr": "increase(events_vote_deleted_total{instance=\"$instance\",replica=\"$replica\"}[$__range])",
       "legendFormat": "vote deleted"
      },
      {
       "expr": "increase(events_wip_state_changed_total{instance=\"$instance\",replica=\"$replica\"}[$__range])",
       "legendFormat": "wip state changed"
      }
     ]
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "System load",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "proc_cpu_system_load{instance=\"$instance\",replica=\"$replica\"}",
       "legendFormat": "system load"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 9, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(proc_cpu_usage{instance=\"$instance\", replica=\"$replica\"}[$__interval])",
       "legendFormat": "used CPUs"
      },
      {
       "expr": "proc_cpu_num_cores{instance=\"$instance\",replica=\"$replica\"}",
       "legendFormat": "available CPUs"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "gauge",
     "gridPos": { "h": 11, "w": 3, "x": 21, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "(rate(proc_cpu_usage{instance=\"$instance\", replica=\"$replica\"}[$__interval]) * 100) / proc_cpu_num_cores{instance=\"$instance\", replica=\"$replica\"}",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "Memory",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "proc_jvm_memory_heap_committed{instance=\"$instance\",replica=\"$replica\"}",
       "legendFormat": "committed heap"
      },
      {
       "expr": "proc_jvm_memory_heap_used{instance=\"$instance\",replica=\"$replica\"}",
       "legendFormat": "used heap"
      },
      {
       "expr": "jgit_block_cache_cache_used{instance=\"$instance\",replica=\"$replica\"}",
       "legendFormat": "JGit block cache"
      },
      {
       "expr": "proc_jvm_memory_non_heap_used{instance=\"$instance\",replica=\"$replica\"}",
       "legendFormat": "used non-heap"
      }
     ]
    },
    {
     "title": "Heap memory",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 9, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "proc_jvm_memory_heap_committed{instance=\"gerrit-test.ad.adasworks.com:443\"}",
       "legendFormat": "committed {{instance}}"
      },
      {
       "expr": "proc_jvm_memory_heap_used{instance=\"gerrit-test.ad.adasworks.com:443\"}",
       "legendFormat": "used {{instance}}"
      },
      {
       "expr": "proc_jvm_memory_heap_committed{instance=\"mycorp.org:443\"}",
       "legendFormat": "committed {{instance}}"
      },
      {
       "expr": "proc_jvm_memory_heap_used{instance=\"mycorp.org:443\"}",
       "legendFormat": "used {{instance}}"
      }
     ]
    },
    {
     "title": "Heap Memory Usage",
     "type": "gauge",
     "gridPos": { "h": 11, "w": 3, "x": 21, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "(proc_jvm_memory_heap_used{instance=\"$instance\",replica=\"$replica\"}/proc_jvm_memory_heap_committed{instance=\"$instance\",replica=\"$replica\"})*100",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "Email queue",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "queue_send_email_scheduled_tasks{instance=\"$instance\",replica=\"$replica\"}",
       "legendFormat": "email threads"
      }
     ]
    }
   ]
  },
  {
   "title": "Java",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Java - % of time spent in GC",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "increase(proc_jvm_gc_time_G1_Young_Generation{instance=\"$instance\",replica=\"$replica\"}[2m])/increase(proc_uptime{instance=\"$instance\",replica=\"$replica\"}[2m])",
       "legendFormat": "gc time G1 young gen"
      },
      {
       "expr": "increase(proc_jvm_gc_time_G1_Old_Generation{instance=\"$instance\",replica=\"$replica\"}[2m])/increase(proc_uptime{instance=\"$instance\",replica=\"$replica\"}[2m])",
       "legendFormat": "gc time G1 old gen"
      },
      {
       "expr": "increase(proc_jvm_gc_time_PS_Scavenge{instance=\"$instance\",replica=\"$replica\"}[2m])/increase(proc_uptime{instance=\"$instance\",replica=\"$replica\"}[2m])",
       "legendFormat": "gc time PS Scavange"
      },
      {
       "expr": "increase(proc_jvm_gc_time_PS_MarkSweep{instance=\"$instance\",replica=\"$replica\"}[2m])/increase(proc_uptime{instance=\"$instance\",replica=\"$replica\"}[2m])",
       "legendFormat": "gc time PS MarkSweep"
      },
      {
       "expr": "increase(proc_jvm_gc_time_ZGC{instance=\"$instance\",replica=\"$replica\"}[2m])/increase(proc_uptime{instance=\"$instance\",replica=\"$replica\"}[2m])",
       "legendFormat": "gc time ZGC"
      },
      {
       "expr": "increase(proc_jvm_gc_time_ShenandoahGC{instance=\"$instance\",replica=\"$replica\"}[2m])/increase(proc_uptime{instance=\"$instance\",replica=\"$replica\"}[2m])",
       "legendFormat": "gc time ShenandoahGC"
      }
     ]
    },
    {
     "title": "Java open file descriptors",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jgit_block_cache_open_files{instance=\"$instance\",replica=\"$replica\"}",
       "legendFormat": "jgit block cache"
      },
      {
       "expr": "proc_num_open_fds{instance=\"$instance\",replica=\"$replica\"}-jgit_block_cache_open_files{instance=\"$instance\",replica=\"$replica\"}",
       "legendFormat": "other"
      }
     ]
    },
    {
     "title": "JGit block cache",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "increase(jgit_block_cache_miss_count{instance=\"$instance\",replica=\"$replica\"}[2m])/(increase(jgit_block_cache_hit_count{instance=\"$instance\",replica=\"$replica\"}[2m])+increase(jgit_block_cache_miss_count{instance=\"$instance\",replica=\"$replica\"}[2m]))",
       "legendFormat": "miss ratio"
      },
      {
       "expr": "increase(jgit_block_cache_eviction_count{instance=\"$instance\",replica=\"$replica\"}[2m])/(increase(jgit_block_cache_hit_count{instance=\"$instance\",replica=\"$replica\"}[2m])+increase(jgit_block_cache_miss_count{instance=\"$instance\",replica=\"$replica\"}[2m]))",
       "legendFormat": "eviction ratio"
      }
     ]
    },
    {
     "title": "Live Threads",
     "type": "bargauge",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "proc_jvm_thread_num_daemon_live{instance=\"$instance\",replica=\"$replica\"}",
       "legendFormat": "current (daemon)"
      },
      {
       "expr": "proc_jvm_thread_num_live{instance=\"$instance\",replica=\"$replica\"}",
       "legendFormat": "current (total)"
      },
      {
       "expr": "proc_jvm_thread_num_peak_live{instance=\"$instance\",replica=\"$replica\"}",
       "legendFormat": "peak"
      }
     ]
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "HTTP Request Error Rate",
   "type": "gauge",
   "description": "Excludes 404 and 401, since these error codes are caused by client behaviour and are overrepresented in the data.",
   "gridPos": { "h": 13, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(increase(http_server_error_count_total_total{instance=\"$instance\", replica=\"$replica\"}[$__interval]) - increase(http_server_error_count_404_total{instance=\"$instance\", replica=\"$replica\"}[$__interval]) - increase(http_server_error_count_401_total{instance=\"$instance\", replica=\"$replica\"}[$__interval])) / (increase(http_server_success_count_total_total{instance=\"$instance\", replica=\"$replica\"}[$__interval]) + increase(http_server_error_count_total_total{instance=\"$instance\", replica=\"$replica\"}[$__interval]) - increase(http_server_error_count_404_total{instance=\"$instance\", replica=\"$replica\"}[$__interval]) - increase(http_server_error_count_401_total{instance=\"$instance\", replica=\"$replica\"}[$__interval]))",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "HTTP response status",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 20, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(http_server_success_count_200_total{instance=\"$instance\", replica=\"$replica\"}[$__interval]) / 2",
     "legendFormat": "200"
    },
    {
     "expr": "increase(http_server_success_count_201_total{instance=\"$instance\", replica=\"$replica\"}[$__interval]) / 2",
     "legendFormat": "201"
    },
    {
     "expr": "increase(http_server_success_count_204_total{instance=\"$instance\", replica=\"$replica\"}[$__interval]) / 2",
     "legendFormat": "204"
    },
    {
     "expr": "increase(http_server_success_count_301_total{instance=\"$instance\", replica=\"$replica\"}[$__interval]) / 2",
     "legendFormat": "301"
    },
    {
     "expr": "increase(http_server_success_count_304_total{instance=\"$instance\", replica=\"$replica\"}[$__interval]) / 2",
     "legendFormat": "304"
    },
    {
     "expr": "increase(http_server_error_count_400_total{instance=\"$instance\", replica=\"$replica\"}[$__interval]) / 2",
     "legendFormat": "400"
    },
    {
     "expr": "increase(http_server_error_count_401_total{instance=\"$instance\", replica=\"$replica\"}[$__interval]) / 2",
     "legendFormat": "401"
    },
    {
     "expr": "increase(http_server_error_count_403_total{instance=\"$instance\", replica=\"$replica\"}[$__interval]) / 2",
     "legendFormat": "403"
    },
    {
     "expr": "increase(http_server_error_count_404_total{instance=\"$instance\", replica=\"$replica\"}[$__interval]) / 2",
     "legendFormat": "404"
    },
    {
     "expr": "increase(http_server_error_count_405_total{instance=\"$instance\", replica=\"$replica\"}[$__interval]) / 2",
     "legendFormat": "405"
    },
    {
     "expr": "increase(http_server_error_count_409_total{instance=\"$instance\", replica=\"$replica\"}[$__interval]) / 2",
     "legendFormat": "409"
    },
    {
     "expr": "increase(http_server_error_count_412_total{instance=\"$instance\", replica=\"$replica\"}[$__interval]) / 2",
     "legendFormat": "412"
    },
    {
     "expr": "increase(http_server_error_count_422_total{instance=\"$instance\", replica=\"$replica\"}[$__interval]) / 2",
     "legendFormat": "422"
    },
    {
     "expr": "increase(http_server_error_count_500_total{instance=\"$instance\", replica=\"$replica\"}[$__interval]) / 2",
     "legendFormat": "500"
    },
    {
     "expr": "increase(http_server_error_count_501_total{instance=\"$instance\", replica=\"$replica\"}[$__interval]) / 2",
     "legendFormat": "501"
    },
    {
     "expr": "increase(http_server_error_count_503_total{instance=\"$instance\", replica=\"$replica\"}[$__interval]) / 2",
     "legendFormat": "503"
    }
   ]
  },
  {
   "title": "REST API latency (0.99 quantile)",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "http_server_rest_api_server_latency_total{quantile=\"0.99\", instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "HTTP threads",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 20, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "http_server_jetty_threadpool_active_threads{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "active threads"
    },
    {
     "expr": "http_server_jetty_threadpool_reserved_threads{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "reserved threads"
    },
    {
     "expr": "http_server_jetty_threadpool_max_pool_size{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "max pool size"
    },
    {
     "expr": "http_server_jetty_threadpool_pool_size{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "pool size"
    }
   ]
  },
  { "title": "Misc for alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "REST API Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "http_server_rest_api_server_latency_total{quantile=\"0.99\", instance=\"$instance\",replica=\"$replica\"}"
    }
   ]
  },
  {
   "title": "HTTP Request Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "(increase(http_server_error_count_total_total{instance=\"$instance\", replica=\"$replica\"}[$__interval]) - increase(http_server_error_count_404_total{instance=\"$instance\", replica=\"$replica\"}[$__interval]) - increase(http_server_error_count_401_total{instance=\"$instance\", replica=\"$replica\"}[$__interval])) / (increase(http_server_success_count_total_total{instance=\"$instance\", replica=\"$replica\"}[$__interval]) + increase(http_server_error_count_total_total{instance=\"$instance\", replica=\"$replica\"}[$__interval]) - increase(http_server_error_count_404_total{instance=\"$instance\", replica=\"$replica\"}[$__interval]) - increase(http_server_error_count_401_total{instance=\"$instance\", replica=\"$replica\"}[$__interval]))"
    }
   ]
  }
 ]
}