{
 "title": "GitLab / Sidekiq",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(up{job=~'git-sidekiq'},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Background Jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(sidekiq_jobs_processed_total)",
     "legendFormat": "Processed"
    },
    { "expr": "max(sidekiq_jobs_failed_total)", "legendFormat": "Failed" },
    {
     "expr": "max(sidekiq_jobs_enqueued_size)",
     "legendFormat": "Enqueued"
    },
    {
     "expr": "max(sidekiq_jobs_scheduled_size)",
     "legendFormat": "Scheduled"
    },
    { "expr": "max(sidekiq_jobs_retry_size)", "legendFormat": "Retry" },
    { "expr": "max(sidekiq_jobs_dead_size)", "legendFormat": "Dead" },
    { "expr": "max(sidekiq_processes_size)", "legendFormat": "Processes" }
   ]
  },
  {
   "title": "Queue Size Top 10",
   "type": "table",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, avg_over_time(sidekiq_queue_size{}[$__interval]))"
    }
   ]
  },
  {
   "title": "Load Balancing Strategy",
   "type": "graph",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (load_balancing_strategy) (rate(sidekiq_load_balancing_count{instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{load_balancing_strategy}}"
    }
   ]
  }
 ]
}