{
 "title": "GitLab / Workhorse",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "git_job_name", "query": "git-workhorse" }
  ]
 },
 "panels": [
  {
   "title": "Http Requests Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Http Requests Latency",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (le) (\n  rate(gitlab_workhorse_http_request_duration_seconds_bucket{job=\"$git_job_name\"}[$__interval])\n)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Http Response Size",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "gitlab_workhorse_http_response_size_bytes_bucket{job=\"$git_job_name\"}"
    }
   ]
  },
  {
   "title": "Http Request Total",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (code,method) (rate(gitlab_workhorse_http_requests_total{job=\"$git_job_name\"}[5m]))",
     "legendFormat": "{{code}}-{{method}}"
    }
   ]
  },
  {
   "title": "Error Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Static Error Response",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (code) (rate(gitlab_workhorse_static_error_responses{job=\"$git_job_name\"}[5m]))",
     "legendFormat": "{{code}}-{{method}}"
    }
   ]
  },
  {
   "title": "Internal API Failure Response Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(gitlab_workhorse_internal_api_failure_response_bytes{job=\"$git_job_name\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Object Storage Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Object Storage Uploads Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (instance,status) (rate(gitlab_workhorse_object_storage_upload_requests{job=\"$git_job_name\"}[5m]))",
     "legendFormat": "{{instance}}-{{status}}"
    }
   ]
  },
  {
   "title": "Object Storage Uploads Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(gitlab_workhorse_object_storage_upload_bytes{job=\"$git_job_name\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}