{
 "title": "K8s / Node / Pods",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(kubernetes_io_hostname)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "query_result(kube_pod_info{node=\"$node\"})"
    }
   },
   {
    "name": "pod_ip",
    "query": {
     "query": "label_values(kube_pod_info,pod_ip)"
    }
   },
   {
    "name": "phase",
    "query": {
     "query": "label_values(kube_pod_status_phase,phase)"
    }
   },
   {
    "name": "image",
    "query": {
     "query": "query_result(container_memory_working_set_bytes{instance=\"$node\", pod=\"$pod\"})"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(pod, kubernetes_io_hostname) (rate(container_cpu_usage_seconds_total{pod!=\"\", namespace=~\".*\", pod=~\"$pod\",instance=~\"^$node$\"}[$__rate_interval]))",
     "legendFormat": "{{pod}} ({{kubernetes_io_hostname}})"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(pod, kubernetes_io_hostname) (container_memory_working_set_bytes{id!=\"/\", pod!=\"\", container!=\"jnlp\", namespace=~\".*\", pod!~\"node-exporter.*\", kubernetes_io_hostname=~\"^$node$\", pod=~\"$pod\"})",
     "legendFormat": "{{pod}} ({{kubernetes_io_hostname}})"
    }
   ]
  },
  {
   "title": "Disk read",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(pod, kubernetes_io_hostname, device) (rate(container_fs_reads_bytes_total{id!=\"/\", pod!=\"\", namespace=~\".*\", pod!~\"node-exporter.*\", kubernetes_io_hostname=~\"^$node$\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{device}} {{pod}} ({{kubernetes_io_hostname}})"
    }
   ]
  },
  {
   "title": "Disk write",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(pod, kubernetes_io_hostname, device) (rate(container_fs_writes_bytes_total{id!=\"/\", pod!=\"\", namespace=~\".*\", pod!~\"node-exporter.*\", kubernetes_io_hostname=~\"^$node$\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{device}} {{pod}} ({{kubernetes_io_hostname}})"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network I/O pressure",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum by(pod, kubernetes_io_hostname) (container_network_receive_bytes_total{id!=\"/\", pod!=\"\", container!=\"jnlp\", namespace=~\".*\", pod!~\"node-exporter.*\", kubernetes_io_hostname=~\"^$node$\", pod=~\"$pod\"})",
       "legendFormat": "{{pod}} ({{kubernetes_io_hostname}})"
      },
      {
       "expr": "- sum by(pod, kubernetes_io_hostname) (container_network_transmit_bytes_total{id!=\"/\", pod!=\"\", container!=\"jnlp\", namespace=~\".*\", pod!~\"node-exporter.*\", kubernetes_io_hostname=~\"^$node$\", pod=~\"$pod\"})",
       "legendFormat": "{{pod}} ({{kubernetes_io_hostname}})"
      }
     ]
    }
   ]
  }
 ]
}