{
 "title": "K8s / Node / Podtemplate",
 "description": "Monitors Kubernetes cluster using Prometheus. Shows overall cluster or Node CPU / Memory / Network/ Filesystem usage as well as individual pod, containers statistics. Uses cAdvisor and kube-state metrics only.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": {
     "query": "label_values(kubernetes_io_hostname)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU usage per podtemplate",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 17, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"aidrive-.*-gpu-.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "aidrive-X-gpu"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"annotationloader-.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "annotationloader"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"scorpio-.*-gpu-.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "scorpio-X-gpu"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"ros-.*-gpu-.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "ros-X-gpu"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"aidrive-build-.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "aidrive-build"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"aisim-build-.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "aisim-build"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"aisim-coverage-.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "aisim-coverage"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"preproc-.*-cpu-.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "preproc-X-cpu"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"bev-.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "bev"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"hdmap.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "hdmap"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"trafficsign-.*-gpu-.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "trafficsign-X-gpu"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"cerberus.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "cerberus"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"roadmodel-.*-gpu-.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "roadmodel-X-gpu"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"ssd-.*-gpu-.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "ssd-X-gpu"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"pytorch-.*-gpu-.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "pytorch-X-gpu"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"backend-postprocess.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "backend-postprocess"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"field-test-postprocess.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "field-test-postprocess"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"bbox3d-.*-gpu-.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "bbox-X-gpu"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"annotationloader.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "annotationloader"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"pseudo-lidar-annotate.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "pseudo-lidar-annotate"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"pseudo_lidar_annotate.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "pseudo-lidar-annotate"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"lidar-annotate.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "lidar-annotate"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"lidar-autoannot.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "lidar-autoannot"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"tl2d-detector.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "tl2d-detector"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"tl3d-detector.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "tl3d-detector"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"saaai.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "saaai"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"autotagger.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "autotagger"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"dcp-rule-execution.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "dcp-rule-execution"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"bevdepth-.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "bevdepth"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"flir-.*-gpu-.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "flir-X-gpu"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"conan-to-saadaa.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "conan-to-saadaa"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"realityfilter.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "realityfilter"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"infra-smoke-test.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "infra-smoke-test"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"run-aa.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "run-aa"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"autoqc.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "autoqc"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"autotag.*\",container=\"autotag\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "autotag"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"leadcar.*\",container=\"leadcar\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "leadcar"
    }
   ]
  },
  {
   "title": "CPU usage per podtemplate",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"aidrive-.*-gpu-.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "aidrive-X-gpu"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"annotationloader-.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "annotationloader"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"scorpio-.*-gpu-.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "scorpio-X-gpu"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"ros-.*-gpu-.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "ros-X-gpu"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"aidrive-build-.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "aidrive-build"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"aisim-build-.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "aisim-build"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"aisim-coverage-.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "aisim-coverage"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"preproc-.*-cpu-.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "preproc-X-cpu"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"bev-.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "bev"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"hdmap.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "hdmap"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"trafficsign-.*-gpu-.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "trafficsign-X-gpu"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"cerberus.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "cerberus"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"roadmodel-.*-gpu-.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "roadmodel-X-gpu"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"ssd-.*-gpu-.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "ssd-X-gpu"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"pytorch-.*-gpu-.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "pytorch-X-gpu"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"backend-postprocess.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "backend-postprocess"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"field-test-postprocess.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "field-test-postprocess"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"bbox3d-.*-gpu-.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "bbox-X-gpu"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"annotationloader.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "annotationloader"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"pseudo-lidar-annotate.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "pseudo-lidar-annotate"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"pseudo_lidar_annotate.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "pseudo-lidar-annotate"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"lidar-annotate.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "lidar-annotate"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"lidar-autoannot.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "lidar-autoannot"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"tl2d-detector.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "tl2d-detector"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"tl3d-detector.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "tl3d-detector"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"saaai.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "saaai"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"autotagger.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "autotagger"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"dcp-rule-execution.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "dcp-rule-execution"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"bevdepth-.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "bevdepth"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"flir-.*-gpu-.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "flir-X-gpu"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"conan-to-saadaa.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "conan-to-saadaa"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"realityfilter.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "realityfilter"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"infra-smoke-test.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "infra-smoke-test"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"run-aa.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "run-aa"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"autoqc.*\",container=\"jnlp\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "autoqc"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"autotag.*\",container=\"autotag\",instance=~\"^$Node$\"}[$__rate_interval])) by (container_cpu_usage_seconds_total)",
     "legendFormat": "autotag"
    }
   ]
  },
  {
   "title": "Memory usage per podtemplate",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 17, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",id!=\"/\",pod=~\"aidrive-.*-gpu-.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "aidrive-X-gpu"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"annotationloader-.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "annotationloader"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"scorpio-.*-gpu-.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "scorpio-X-gpu"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"ros-.*-gpu-.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "ros-X-gpu"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"aidrive-build-.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "aidrive-build"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"aisim-build-.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "aisim-build"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"aisim-coverage-.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "aisim-coverage"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"preproc-.*-cpu-.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "preproc-X-cpu"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"bev-.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "bev"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"hdmap.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "hdmap"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"trafficsign-.*-gpu-.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "trafficsign-X-gpu"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"cerberus.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "cerberus"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"roadmodel-.*-gpu-.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "roadmodel-X-gpu"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"ssd-.*-gpu-.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "ssd-X-gpu"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"pytorch-.*-gpu-.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "pytorch-X-gpu"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"backend-postprocess.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "backend-postprocess"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"field-test-postprocess.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "field-test-postprocess"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"bbox3d-.*-gpu-.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "bbox-X-gpu"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"annotationloader.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "annotationloader"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"pseudo-lidar-annotate.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "pseudo-lidar-annotate"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"pseudo_lidar_annotate.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "pseudo-lidar-annotate"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"lidar-annotate.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "lidar-annotate"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"lidar-autoannot.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "lidar-autoannot"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"tl2d-detector.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "tl2d-detector"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"tl3d-detector.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "tl3d-detector"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"saaai.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "saaai"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"autotagger.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "autotagger"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"dcp-rule-execution.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "dcp-rule-execution"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"bevdepth-.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "bevdepth"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"flir-.*-gpu-.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "flir-X-gpu"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"conan-to-saadaa.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "conan-to-saadaa"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"realityfilter.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "realityfilter"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"infra-smoke-test.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "infra-smoke-test"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"run-aa.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "run-aa"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"autoqc.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "autoqc"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"autotag.*\",container=\"autotag\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "autotag"
    }
   ]
  },
  {
   "title": "Memory usage per podtemplate",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 7, "x": 17, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",id!=\"/\",pod=~\"aidrive-.*-gpu-.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "aidrive-X-gpu"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"annotationloader-.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "annotationloader"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"scorpio-.*-gpu-.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "scorpio-X-gpu"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"ros-.*-gpu-.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "ros-X-gpu"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"aidrive-build-.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "aidrive-build"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"aisim-build-.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "aisim-build"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"aisim-coverage-.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "aisim-coverage"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"preproc-.*-cpu-.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "preproc-X-cpu"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"bev-.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "bev"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"hdmap.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "hdmap"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"trafficsign-.*-gpu-.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "trafficsign-X-gpu"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"cerberus.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "cerberus"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"roadmodel-.*-gpu-.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "roadmodel-X-gpu"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"ssd-.*-gpu-.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "ssd-X-gpu"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"pytorch-.*-gpu-.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "pytorch-X-gpu"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"backend-postprocess.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "backend-postprocess"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"field-test-postprocess.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "field-test-postprocess"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"bbox3d-.*-gpu-.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "bbox-X-gpu"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"annotationloader.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "annotationloader"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"pseudo-lidar-annotate.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "pseudo-lidar-annotate"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"pseudo_lidar_annotate.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "pseudo-lidar-annotate"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"lidar-annotate.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "lidar-annotate"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"lidar-autoannot.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "lidar-autoannot"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"tl2d-detector.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "tl2d-detector"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"tl3d-detector.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "tl3d-detector"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"saaai.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "saaai"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"autotagger.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "autotagger"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"dcp-rule-execution.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "dcp-rule-execution"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"bevdepth-.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "bevdepth"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"flir-.*-gpu-.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "flir-X-gpu"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"conan-to-saadaa.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "conan-to-saadaa"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"realityfilter.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "realityfilter"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"infra-smoke-test.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "infra-smoke-test"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"run-aa.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "run-aa"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"autoqc.*\",container=\"jnlp\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "autoqc"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",pod=~\"autotag.*\",container=\"autotag\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_memory_working_set_bytes)",
     "legendFormat": "autotag"
    }
   ]
  },
  {
   "title": "GPU usage per podtemplate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 17, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"aidrive-.*-gpu-.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "aidrive-X-gpu"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"annotationloader-.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "annotationloader"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"scorpio-.*-gpu-.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "scorpio-X-gpu"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"ros-.*-gpu-.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "ros-X-gpu"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"aidrive-build-.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "aidrive-build"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"aisim-build-.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "aisim-build"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"aisim-coverage-.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "aisim-coverage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"preproc-.*-cpu-.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "preproc-X-cpu"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"bev-.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "bev"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"hdmap.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "hdmap"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"trafficsign-.*-gpu-.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "trafficsign-X-gpu"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"cerberus.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "cerberus"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"roadmodel-.*-gpu-.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "roadmodel-X-gpu"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"ssd-.*-gpu-.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "ssd-X-gpu"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"pytorch-.*-gpu-.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "pytorch-X-gpu"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"backend-postprocess.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "backend-postprocess"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"field-test-postprocess.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "field-test-postprocess"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"bbox3d-.*-gpu-.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "bbox-X-gpu"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"annotationloader.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "annotationloader"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"pseudo-lidar-annotate.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "pseudo-lidar-annotate"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"pseudo_lidar_annotate.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "pseudo-lidar-annotate"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"lidar-annotate.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "lidar-annotate"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"lidar-autoannot.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "lidar-autoannot"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"tl2d-detector.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "tl2d-detector"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"tl3d-detector.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "tl3d-detector"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"saaai.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "saaai"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"autotagger.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "autotagger"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"dcp-rule-execution.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "dcp-rule-execution"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"bevdepth-.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "bevdepth"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"flir-.*-gpu-.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "flir-X-gpu"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"conan-to-saadaa.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "conan-to-saadaa"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"realityfilter.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "realityfilter"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"infra-smoke-test.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "infra-smoke-test"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"run-aa.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "run-aa"
    },
    {
     "expr": "sum(container_cpu_usage_seconds_total{pod=\"autoqc.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "autoqc"
    }
   ]
  },
  {
   "title": "GPU usage per podtemplate",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 7, "x": 17, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"aidrive-.*-gpu-.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "aidrive-X-gpu"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"annotationloader-.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "annotationloader"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"scorpio-.*-gpu-.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "scorpio-X-gpu"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"ros-.*-gpu-.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "ros-X-gpu"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"aidrive-build-.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "aidrive-build"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"aisim-build-.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "aisim-build"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"aisim-coverage-.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "aisim-coverage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"preproc-.*-cpu-.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "preproc-X-cpu"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"bev-.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "bev"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"hdmap.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "hdmap"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"trafficsign-.*-gpu-.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "trafficsign-X-gpu"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"cerberus.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "cerberus"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"roadmodel-.*-gpu-.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "roadmodel-X-gpu"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"ssd-.*-gpu-.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "ssd-X-gpu"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"pytorch-.*-gpu-.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "pytorch-X-gpu"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"backend-postprocess.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "backend-postprocess"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"field-test-postprocess.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "field-test-postprocess"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"bbox3d-.*-gpu-.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "bbox-X-gpu"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"annotationloader.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "annotationloader"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"pseudo-lidar-annotate.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "pseudo-lidar-annotate"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"pseudo_lidar_annotate.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "pseudo-lidar-annotate"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"lidar-annotate.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "lidar-annotate"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"lidar-autoannot.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "lidar-autoannot"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"tl2d-detector.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "tl2d-detector"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"tl3d-detector.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "tl3d-detector"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"saaai.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "saaai"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"autotagger.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "autotagger"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"dcp-rule-execution.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "dcp-rule-execution"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"bevdepth-.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "bevdepth"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"flir-.*-gpu-.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "flir-X-gpu"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"conan-to-saadaa.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "conan-to-saadaa"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"realityfilter.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "realityfilter"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"infra-smoke-test.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "infra-smoke-test"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"run-aa.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "run-aa"
    },
    {
     "expr": "sum(container_cpu_usage_seconds_total{pod=\"autoqc.*\",node=~\"^$Node$\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "autoqc"
    }
   ]
  }
 ]
}