{
 "title": "K8s / System / API Server",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "resolution", "query": "1s, 15s, 30s, 1m, 3m, 5m" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "API server - Health status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"kubernetes-apiservers\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Deprecated kubernetes resources",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "apiserver_requested_deprecated_apis"
    }
   ]
  },
  {
   "title": "API server - HTTP requests by code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (code) (rate(apiserver_request_total[$__rate_interval]))",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "API server - HTTP requests by verb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (verb) (rate(apiserver_request_total[$__rate_interval]))",
     "legendFormat": "{{ verb}}"
    }
   ]
  },
  {
   "title": "API server - HTTP requests latency by instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_duration_seconds_bucket{job=\"kubernetes-apiservers\"}[$__rate_interval])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "API server - HTTP requests latency by verb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_duration_seconds_bucket{job=\"kubernetes-apiservers\"}[$__rate_interval])) by (verb)",
     "legendFormat": "{{ verb }}"
    }
   ]
  },
  {
   "title": "API server - Errors by Instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(apiserver_request_total{code=~\"5..\", job=\"kubernetes-apiservers\"}[$__rate_interval]))\n / sum by(instance) (rate(apiserver_request_total{job=\"kubernetes-apiservers\"}[$__rate_interval]))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "API Server - Errors by verb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(verb) (rate(apiserver_request_total{code=~\"5..\",job=\"kubernetes-apiservers\"}[$__rate_interval]))\n / sum by(verb) (rate(apiserver_request_total{job=\"kubernetes-apiservers\"}[$__rate_interval]))",
     "legendFormat": "{{ verb }}"
    }
   ]
  },
  {
   "title": "API server - Stacked HTTP requests by instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total[$__rate_interval])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "API server - Work queue by instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(workqueue_depth{job=\"kubernetes-apiservers\"}[$__rate_interval])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "API Server - CPU usage by instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"kubernetes-apiservers\"}[$__rate_interval])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "API Server - Memory usage by instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"kubernetes-apiservers\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}