{
 "title": "K8s / Pods",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "pod", "query": { "query": "label_values(pod)" } },
   {
    "name": "pod_ip",
    "query": {
     "query": "label_values(kube_pod_info{pod=\"$pod\"},pod_ip)"
    }
   },
   {
    "name": "image",
    "query": {
     "query": "label_values(kube_pod_container_info{pod=\"$pod\"},image)"
    }
   },
   {
    "name": "pod_template",
    "query": {
     "query": "label_values(kube_pod_labels{pod=\"$pod\"},label_jenkins_label)"
    }
   },
   {
    "name": "node_name",
    "query": {
     "query": "label_values(kube_pod_info{pod=\"$pod\"},node)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_pod_info,cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Pod info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pod Template",
   "type": "text",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "content": "# $pod_template" },
   "targets": [
    {}
   ]
  },
  {
   "title": "Container ready",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Container running",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_running{pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Container terminated",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_terminated{pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Container waiting",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_waiting{pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Container restarts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Pod IP address",
   "type": "text",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "options": { "content": "# $pod_ip" },
   "targets": [
    {}
   ]
  },
  {
   "title": "Node name",
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 5 },
   "options": { "content": "# $node_name" },
   "targets": [
    {}
   ]
  },
  {
   "title": "Image",
   "type": "text",
   "gridPos": { "h": 3, "w": 18, "x": 6, "y": 5 },
   "options": { "content": "# $image" },
   "targets": [
    {}
   ]
  },
  {
   "title": "Image status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Last terminated reason",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 6, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_last_terminated_reason{pod=\"$pod\"}) by (reason)",
       "legendFormat": "{{ reason }}"
      }
     ]
    },
    {
     "title": "Terminated reason",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 6, "x": 6, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_terminated_reason{pod=\"$pod\"}) by (reason)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Waiting reason",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 6, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_waiting_reason{pod=\"$pod\"}) by (reason)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "State",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 6, "x": 18, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_ready{pod=\"$pod\"})",
       "legendFormat": "Ready"
      },
      {
       "expr": "sum(kube_pod_container_status_running{pod=\"$pod\"})",
       "legendFormat": "Running"
      },
      {
       "expr": "sum(kube_pod_container_status_waiting{pod=\"$pod\"})",
       "legendFormat": "Waiting"
      },
      {
       "expr": "sum(kube_pod_container_status_restarts_total{pod=\"$pod\"})",
       "legendFormat": "Restarts Total"
      },
      {
       "expr": "sum(kube_pod_container_status_terminated{pod=\"$pod\"})",
       "legendFormat": "Terminated"
      }
     ]
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(pod, kubernetes_io_hostname) (rate(container_cpu_usage_seconds_total{pod!=\"\", namespace=~\".*\", pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "Use"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores{cluster=\"$cluster\", pod=\"$pod\"}) by (pod)",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Memory usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by(pod, kubernetes_io_hostname) (container_memory_working_set_bytes{id!=\"/\", pod!=\"\", container!=\"jnlp\", namespace=~\".*\", pod!~\"node-exporter.*\", pod=~\"$pod\"})",
       "legendFormat": "Use"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{cluster=\"$cluster\", pod=\"$pod\"}) by (pod)",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Disk read",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by(pod, kubernetes_io_hostname, device) (rate(container_fs_reads_bytes_total{id!=\"/\", pod!=\"\", namespace=~\".*\", pod!~\"node-exporter.*\", pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Disk write",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by(pod, kubernetes_io_hostname, device) (rate(container_fs_writes_bytes_total{id!=\"/\", pod!=\"\", namespace=~\".*\", pod!~\"node-exporter.*\", pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "{{device}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network I/O pressure",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum by(pod, kubernetes_io_hostname) (container_network_receive_bytes_total{id!=\"/\", pod!=\"\", container!=\"jnlp\", namespace=~\".*\", pod!~\"node-exporter.*\", pod=~\"$pod\"})",
       "legendFormat": "Receive"
      },
      {
       "expr": "- sum by(pod, kubernetes_io_hostname) (container_network_transmit_bytes_total{id!=\"/\", pod!=\"\", container!=\"jnlp\", namespace=~\".*\", pod!~\"node-exporter.*\", pod=~\"$pod\"})",
       "legendFormat": "Transmit"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU count",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "kube_pod_container_resource_requests{pod=\"$pod\", resource=\"nvidia_com_gpu\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "GPU temperature",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "DCGM_FI_DEV_GPU_TEMP{pod=\"$pod\"}",
       "legendFormat": "Node: {{instance}} | ModelName: {{modelName}} | Slot {{gpu}}"
      }
     ]
    },
    {
     "title": "GPU power usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "DCGM_FI_DEV_POWER_USAGE{pod=\"$pod\"}",
       "legendFormat": "Node: {{instance}} | ModelName: {{modelName}} | Slot {{gpu}}"
      }
     ]
    },
    {
     "title": "GPU framebuffer mem used",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "DCGM_FI_DEV_FB_USED{pod=\"$pod\"}",
       "legendFormat": "Node: {{instance}} | ModelName: {{modelName}} | Slot {{gpu}}"
      }
     ]
    },
    {
     "title": "GPU SM clocks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "hertz" } },
     "targets": [
      {
       "expr": "DCGM_FI_DEV_SM_CLOCK{pod=\"$pod\"} * 1000000",
       "legendFormat": "Node: {{instance}} | ModelName: {{modelName}} | Slot {{gpu}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Quota",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Quota",
     "type": "table-old",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 62 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(container_cpu_usage_seconds_total{cluster=\"$cluster\", pod=\"$pod\"}) by (pod)"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{cluster=\"$cluster\", pod=\"$pod\"}) by (pod)"
      },
      {
       "expr": "sum(container_cpu_usage_seconds_total{cluster=\"$cluster\", pod=\"$pod\"}) by (pod) / sum(kube_pod_container_resource_requests_cpu_cores{cluster=\"$cluster\", pod=\"$pod\"}) by (pod)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores{cluster=\"$cluster\", pod=\"$pod\"}) by (pod)"
      },
      {
       "expr": "sum(container_cpu_usage_seconds_total{cluster=\"$cluster\", pod=\"$pod\"}) by (pod) / sum(kube_pod_container_resource_limits_cpu_cores{cluster=\"$cluster\", pod=\"$pod\"}) by (pod)"
      }
     ]
    },
    {
     "title": "Memory Quota",
     "type": "table-old",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 66 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\", pod=\"$pod\",container!=\"\"}) by (pod)"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{cluster=\"$cluster\", pod=\"$pod\"}) by (pod)"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\", pod=\"$pod\",container!=\"\"}) by (pod) / sum(kube_pod_container_resource_requests_memory_bytes{pod=\"$pod\"}) by (pod)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{cluster=\"$cluster\", pod=\"$pod\"}) by (pod)"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\", pod=\"$pod\",container!=\"\"}) by (pod) / sum(kube_pod_container_resource_limits_memory_bytes{pod=\"$pod\"}) by (pod)"
      },
      {
       "expr": "sum(container_memory_rss{cluster=\"$cluster\", pod=\"$pod\",container!=\"\"}) by (pod)"
      },
      {
       "expr": "sum(container_memory_cache{cluster=\"$cluster\", pod=\"$pod\",container!=\"\"}) by (pod)"
      },
      {
       "expr": "sum(container_memory_swap{cluster=\"$cluster\", pod=\"$pod\",container!=\"\"}) by (pod)"
      }
     ]
    }
   ]
  }
 ]
}