{
 "title": "SSL / Expiration date",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Traefik certificates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Hosted services certificates expiry date",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "ssl_cert_not_after{cn=~\".*mycorp.*\"}*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hosted services certificates expiry time left",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "ssl_cert_not_after{cn=~\".*mycorp.*\"} - time()",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kubernetes internal certificates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "Kubernetes certifications expiry",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "ssl_file_cert_not_after{cn!~\".*cygnus.*\"}*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kubernetes certification expiry time left",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "ssl_file_cert_not_after{cn!~\".*cygnus.*\"} - time()",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Alert panels", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Alert if less than 2 weeks until expiry",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "ssl_file_cert_not_after{cn!~\".*cygnus.*\"} - time()",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alert if less than 2 weeks until expiry of hosted cert",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "ssl_cert_not_after{cn=~\".*mycorp.*\"} - time()",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}